server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  profiles:
    active: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weekly-report?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: root

  hikari:
    connection-timeout: 30000
    minimum-idle: 5
    maximum-pool-size: 20
    auto-commit: true
    idle-timeout: 600000
    pool-name: DataSourceHikariCP
    max-lifetime: 1800000
    connection-test-query: SELECT 1

  redis:
    database: 0
    host: localhost
    port: 6379
    password: Netvine123#@!

  servlet:
    multipart:
      max-file-size: 512000
      max-request-size: 512000

# 通用 Mapper 配置
mapper:
  mappers: com.netvine.weeklyreport.common.mapper.MyMapper
  not-empty: false
  identity: MYSQL

mybatis:
  type-aliases-package: com.netvine.weeklyreport
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

